[2025-08-22T16:37:13.717+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-22T16:37:13.725+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_setup manual__2025-08-22T16:37:03.947651+00:00 [queued]>
[2025-08-22T16:37:13.729+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_setup manual__2025-08-22T16:37:03.947651+00:00 [queued]>
[2025-08-22T16:37:13.729+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-08-22T16:37:13.735+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_setup> on 2025-08-22 16:37:03.947651+00:00
[2025-08-22T16:37:13.737+0000] {standard_task_runner.py:72} INFO - Started process 142 to run task
[2025-08-22T16:37:13.739+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'espn_news_pipeline', 'dbt_setup', 'manual__2025-08-22T16:37:03.947651+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmp09klmz2r']
[2025-08-22T16:37:13.740+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask dbt_setup
[2025-08-22T16:37:13.766+0000] {task_command.py:467} INFO - Running <TaskInstance: espn_news_pipeline.dbt_setup manual__2025-08-22T16:37:03.947651+00:00 [running]> on host 83371497f108
[2025-08-22T16:37:13.805+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='espn_news_pipeline' AIRFLOW_CTX_TASK_ID='dbt_setup' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T16:37:03.947651+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T16:37:03.947651+00:00'
[2025-08-22T16:37:13.806+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-22T16:37:13.811+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-22T16:37:13.812+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd $DBT_PROJECT_DIR && dbt deps']
[2025-08-22T16:37:13.816+0000] {subprocess.py:86} INFO - Output:
[2025-08-22T16:37:13.817+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-08-22T16:37:13.817+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-08-22T16:37:13.824+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-08-22T16:37:13.826+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=espn_news_pipeline, task_id=dbt_setup, run_id=manual__2025-08-22T16:37:03.947651+00:00, execution_date=20250822T163703, start_date=20250822T163713, end_date=20250822T163713
[2025-08-22T16:37:13.832+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-22T16:37:13.832+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task dbt_setup (Bash command failed. The command returned a non-zero exit code 127.; 142)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-08-22T16:37:13.839+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-22T16:37:13.851+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-22T16:37:13.853+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
