[2025-08-22T17:11:24.309+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-22T17:11:24.316+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_run manual__2025-08-22T17:11:10.507470+00:00 [queued]>
[2025-08-22T17:11:24.319+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_run manual__2025-08-22T17:11:10.507470+00:00 [queued]>
[2025-08-22T17:11:24.319+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-08-22T17:11:24.324+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run> on 2025-08-22 17:11:10.507470+00:00
[2025-08-22T17:11:24.326+0000] {standard_task_runner.py:72} INFO - Started process 62 to run task
[2025-08-22T17:11:24.327+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'espn_news_pipeline', 'dbt_run', 'manual__2025-08-22T17:11:10.507470+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmp7o2arn75']
[2025-08-22T17:11:24.329+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask dbt_run
[2025-08-22T17:11:24.351+0000] {task_command.py:467} INFO - Running <TaskInstance: espn_news_pipeline.dbt_run manual__2025-08-22T17:11:10.507470+00:00 [running]> on host 9594dc760a36
[2025-08-22T17:11:24.384+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='espn_news_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T17:11:10.507470+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T17:11:10.507470+00:00'
[2025-08-22T17:11:24.384+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-22T17:11:24.389+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-22T17:11:24.389+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd $DBT_PROJECT_DIR && /home/***/.local/bin/dbt run']
[2025-08-22T17:11:24.393+0000] {subprocess.py:86} INFO - Output:
[2025-08-22T17:11:25.247+0000] {subprocess.py:93} INFO - [0m17:11:25  Running with dbt=1.8.6
[2025-08-22T17:11:25.629+0000] {subprocess.py:93} INFO - [0m17:11:25  Registered adapter: snowflake=1.8.3
[2025-08-22T17:11:25.704+0000] {subprocess.py:93} INFO - [0m17:11:25  Unable to do partial parsing because of a version mismatch
[2025-08-22T17:11:26.104+0000] {subprocess.py:93} INFO - [0m17:11:26  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-08-22T17:11:26.105+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-08-22T17:11:26.105+0000] {subprocess.py:93} INFO - - models.espn_project.example
[2025-08-22T17:11:26.146+0000] {subprocess.py:93} INFO - [0m17:11:26  Found 7 models, 459 macros
[2025-08-22T17:11:26.147+0000] {subprocess.py:93} INFO - [0m17:11:26
[2025-08-22T17:11:26.855+0000] {subprocess.py:93} INFO - [0m17:11:26
[2025-08-22T17:11:26.856+0000] {subprocess.py:93} INFO - [0m17:11:26  Finished running  in 0 hours 0 minutes and 0.71 seconds (0.71s).
[2025-08-22T17:11:26.857+0000] {subprocess.py:93} INFO - [0m17:11:26  Encountered an error:
[2025-08-22T17:11:26.857+0000] {subprocess.py:93} INFO - Runtime Error
[2025-08-22T17:11:26.858+0000] {subprocess.py:93} INFO -   Database error while listing schemas in database "ESPN_DB"
[2025-08-22T17:11:26.858+0000] {subprocess.py:93} INFO -   Database Error
[2025-08-22T17:11:26.859+0000] {subprocess.py:93} INFO -     002043 (02000): SQL compilation error:
[2025-08-22T17:11:26.859+0000] {subprocess.py:93} INFO -     Object does not exist, or operation cannot be performed.
[2025-08-22T17:11:27.349+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-22T17:11:27.355+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-22T17:11:27.357+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=espn_news_pipeline, task_id=dbt_run, run_id=manual__2025-08-22T17:11:10.507470+00:00, execution_date=20250822T171110, start_date=20250822T171124, end_date=20250822T171127
[2025-08-22T17:11:27.362+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-22T17:11:27.362+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 20 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 62)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-22T17:11:27.396+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-22T17:11:27.406+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-22T17:11:27.407+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
