[2025-09-21T07:23:04.862+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-21T07:23:04.871+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_run manual__2025-09-21T07:22:51.635782+00:00 [queued]>
[2025-09-21T07:23:04.873+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_run manual__2025-09-21T07:22:51.635782+00:00 [queued]>
[2025-09-21T07:23:04.873+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-21T07:23:04.877+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-09-21 07:22:51.635782+00:00
[2025-09-21T07:23:04.879+0000] {standard_task_runner.py:64} INFO - Started process 417 to run task
[2025-09-21T07:23:04.881+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'espn_news_pipeline', 'dbt_run', 'manual__2025-09-21T07:22:51.635782+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmp2gf2xl0t']
[2025-09-21T07:23:04.882+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask dbt_run
[2025-09-21T07:23:04.894+0000] {task_command.py:426} INFO - Running <TaskInstance: espn_news_pipeline.dbt_run manual__2025-09-21T07:22:51.635782+00:00 [running]> on host ec82c1b2067c
[2025-09-21T07:23:04.914+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='espn_news_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T07:22:51.635782+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-21T07:22:51.635782+00:00'
[2025-09-21T07:23:04.915+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-21T07:23:04.919+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-21T07:23:04.919+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd $DBT_PROJECT_DIR && /home/airflow/.local/bin/dbt run']
[2025-09-21T07:23:04.922+0000] {subprocess.py:86} INFO - Output:
[2025-09-21T07:23:05.759+0000] {subprocess.py:93} INFO - [0m07:23:05  Running with dbt=1.8.9
[2025-09-21T07:23:06.153+0000] {subprocess.py:93} INFO - [0m07:23:06  Registered adapter: snowflake=1.8.4
[2025-09-21T07:23:06.242+0000] {subprocess.py:93} INFO - [0m07:23:06  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-21T07:23:06.242+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-21T07:23:06.242+0000] {subprocess.py:93} INFO - - models.espn_project.example
[2025-09-21T07:23:06.289+0000] {subprocess.py:93} INFO - [0m07:23:06  Found 7 models, 464 macros
[2025-09-21T07:23:06.290+0000] {subprocess.py:93} INFO - [0m07:23:06
[2025-09-21T07:23:06.302+0000] {subprocess.py:93} INFO - [0m07:23:06
[2025-09-21T07:23:06.302+0000] {subprocess.py:93} INFO - [0m07:23:06  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-09-21T07:23:06.302+0000] {subprocess.py:93} INFO - [0m07:23:06  Encountered an error:
[2025-09-21T07:23:06.302+0000] {subprocess.py:93} INFO - Runtime Error
[2025-09-21T07:23:06.303+0000] {subprocess.py:93} INFO -   Database error while listing schemas in database "API_DATA_DB"
[2025-09-21T07:23:06.303+0000] {subprocess.py:93} INFO -   Database Error
[2025-09-21T07:23:06.303+0000] {subprocess.py:93} INFO -     [Errno 2] No such file or directory: '/opt/airflow/airflow/keys/rsa_key.p8'
[2025-09-21T07:23:06.864+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-09-21T07:23:06.864+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-21T07:23:06.867+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-21T07:23:06.869+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=espn_news_pipeline, task_id=dbt_run, run_id=manual__2025-09-21T07:22:51.635782+00:00, execution_date=20250921T072251, start_date=20250921T072304, end_date=20250921T072306
[2025-09-21T07:23:06.873+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 417)
[2025-09-21T07:23:06.879+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-21T07:23:06.886+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-21T07:23:06.888+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
